[header]
lang = "en"
title = "Florian Vichot - CV"
headline = "Florian Vichot"
subtext = "experienced software developer"
location = "Paris, France"
phone = "+33 6 62 04 94 38"
email = "florian.vichot@gmail.com"
description = "An accomplished software developer, I have more than ten years of experience, comprising professional and personal projects. Fluent in multiple languages - including C, C++ and Python - I strive foremost to be versatile, and to be able to efficiently solve a broad range of problems. While drawn primarily to the roles of devOps, backend or infrastructure engineer, I welcome all opportunities that would allow me to work on challenging problems as part of a talented team. Projects with an open-source model or tackling social issues are especially attractive."

github = "[fvichot](https://github.com/fvichot)"
stackoverflow = "[florian](http://stackoverflow.com/users/2984/florian)"
linkedin = "[fvichot](https://linkedin.com/in/fvichot)"

###################################################################################################

[experience]
headline = "Experience"

[[experience.item]]
title = "Software & Network Engineer"
company = "[Wifirst](http://wifirst.fr/)"
location = "Paris, France"
date = "April 2016 to present"
highlights = [
"Developing new functionalities and tools in Python for a custom network router, to provide traffic shaping, access control and monitoring for our customers.",
"Supervision of a fleet of 9,000 routers, managed through Ansible.",
"Testing and selecting new hardware for the router.", 
"Porting the services and OS used on our custom router to a new architecture based on a Broadcom SoC.", 
"Adding new functionalities and fixing bugs in in-house software, such as our monitoring dashboard and configuration management database.",
"[Speaker](https://www.youtube.com/watch?v=0uasvz2DYos) at PyCon France 2017",
]
tags = ["Python", "Asyncio", "Django", "Bash", "Git", "Ansible", "iptables", "SNMP", "QoS", "VLAN", "WiFI", "Network", "Embedded Linux"]

[[experience.item]]
title = "Expert Engineer"
company = "[Inria, Asclepios Lab](https://team.inria.fr/asclepios/)"
location = "Sophia-Antipolis, France"
date = "March 2012 to April 2015"
highlights = [
"Lead developer on [medInria](http://med.inria.fr), an open-source medical image visualisation, processing and manipulation software, to add cardiac related functionalities.",
"Contributed to improving the reliability of medInria, and its code quality by instituting code-reviews and a pull-request based workflow. Migrated the project to GitHub, reorganised, cleaned and simplified the source code, re-architected and updated the build/test system.",
"Evolved medInria's architecture to handle new functionalities, and transformed it into a framework for other projects using a plugin system.",
"Attended conferences (MICCAI), workshops (CTK), and contributed to scientific articles."
]
tags = ["C++", "Python", "Bash", "Git", "CMake", "Jenkins", "Open-Source", "Qt", "VTK", "ITK", "Mac", "Windows", "Linux"]

[[experience.item]]
title = "Telecoms & Network Engineer"
company = "[Telecoms Without Borders](http://www.tsfi.org/)"
location = "Pau, France"
date = "Sept. 2010 to Oct. 2011, April 2015"
highlights = [
"Deployed on various international missions in response to humanitarian emergencies: floods, influx of refugees, cyclone, conflict or famine, for a total of 5 months on mission. Established telephone operations for populations, installed network and satellite equipment for NGOs and the UN. Provided trainings.",
"Contributed to the TSFBox, a network router facilitating monitoring and optimization of internet connections provided during missions."
]
tags = ["Perl", "Python", "Bash", "iptables", "System administration", "Networks", "Satellites", "Linux"]


[[experience.item]]
title = "Developer"
company = "[Diateam](http://www.diateam.net/)"
location = "Brest, France"
date = "June 2008 to April 2010, July/August 2007"
highlights = [
"Lead developer on the [Hynesim](http://www.hynesim.com/) (Hybrid Network Simulator) and contributor to the [IpMorph](http://www.diateam.net/Labo-334-0-0-0.html) (TCP/IP stack fingerprint spoofing) open-source projects. Speaker on IpMorph during Hack.lu 2009.",
"Developer on [Diabox](http://data.diabox.com/), an in-situ sensor box, used primarily for weather data.",
"Developer on [Naiad](http://naiad.ifremer.fr/) (Enhanced Satellite Archive Dataminer), an application to visualise and process satellite data for the IFREMER institute. Prototyped various image filters on GPU using OpenCL."
]
tags = ["C", "C++", "Python", "Open-Source", "Qt", "Multi-Thread", "Container", "Virtualisation", "OpenCL", "Mac", "Windows", "Linux"]

[[experience.item]]
title = "Internship"
company = "[Cognitive Robotics Lab (ENSTA)](http://cogrob.ensta-paristech.fr/)"
location = "Paris, France"
date = "Sept. 2007 to Jan. 2008"
highlights = [
"Implemented visual homing and localization algorithms using \"bags of visual words\" in [Urbi](https://en.wikipedia.org/wiki/URBI), as part of a topological navigation framework.",
"Ported the Urbi environment to a P3-DX robot.",
"This work was included in a [scientific publication](https://hal-ensta.archives-ouvertes.fr/hal-00641356)."
]
tags = ["C", "C++", "Urbi", "SVN", "Machine-Learning", "Linux", "Robotics"]

###################################################################################################

[projects]
headline = "Personal Projects"

[[projects.item]]
title = "Robotics Club"
company = "[ENIB](https://www.enib.fr/)"
location = "Brest, France"
date = "2004 to 2010"
highlights = [
"Club secretary: sponsors engagement, communication, project management.",
"Lead developer on the robot's software (simulator, sensor acquisition, path planning, motor control)"
]
tags = ["C", "C++", "Qt", "OpenGL", "SVN", "Linux", "Embedded", "Robotics"]

[[projects.item]]
title = "Server management"
date = "2011 to 2015"
highlights = [
"Administrator of a server shared with a group of friends: configuration, hardening (no breach in five years)."
]
tags = ["Linux Debian", "SSH", "iptables", "Apache", "PHP", "OwnCloud", "OpenVPN", "IMAP", "SMTP", "LVM", "LUKS", "KVM", "LXC"]

###################################################################################################

[skills]
headline = "Skills"
high = "Excellent"
medium = "Good"
low = "Basic"

[[skills.item]]
headline = "Languages"
high = ["C", "C++", "Python", "Bash"]
medium = ["Go", "JavaScript", "Java", "Octave"]
low = ["OCaml", "Rust", "Prolog"]

[[skills.item]]
headline = "Tools and concepts"
high = ["Qt", "Git", "SVN", "CMake", "Multi-threading", "Robotics"]
medium = ["OpenGL", "OpenCL", "SQL", "Algorithms", "Optimisation"]

[[skills.item]]
headline = "Networks & Servers"
high = ["Internet protocols", "Server admin", "Security"]
medium = ["SSL", "AWS", "Satellite systems"]

[[skills.item]]
headline = "Platforms"
high = ["Linux", "Mac OS X", "Windows"]
low = ["Android", "OpenBSD"]

###################################################################################################

[languages]
headline = "Languages"

[[languages.item]]
name = "French"
level = "Fluent (French citizen)"

[[languages.item]]
name = "English"
level = "Fluent (studied for three years in the UK, TOEFL iBT: 119/120, PTE: 90/90)"

[[languages.item]]
name = "Spanish"
level = "Intermediate (six months in South America)"

###################################################################################################

[education]
headline = "Education"
highlights = [
"[ENIB](https://www.enib.fr/en/), National Engineering School of Brest, France from 2003 to 2008 (Master's Degree in Engineering).",
"Artificial Intelligence online course, University of Stanford, 2012.",
"Machine Learning online course, Stanford University, 2015 ([Coursera](https://www.coursera.org/learn/machine-learning))."
]

###################################################################################################

[publications]
headline = "Publications"
authors = "Authors"
abstract = "Summary"

[[publications.item]]
title = "[Cardiac Interventional Guidance using Multimodal Data Processing and Visualisation: medInria as an Interoperability Platform](https://hal.inria.fr/hal-00813873/)"
publisher = "Midas Journal"
date = "2012"
authors = "F. Vichot, H. Cochet, B. Bleuzé, N. Toussaint, P. Jaïs, M. Sermesant"
abstract = "MedInria is a medical imaging software developed at Inria, which aims to provide clinicians with state-of-the-art algorithms for processing and visualising their images. In this article, we will focus on its use in pre-surgery preparation for cardiac interventions, and the difficulties arising from the lack of standardisation of certain data formats and visualisation conventions."

[[publications.item]]
title = "[IpMorph: fingerprinting spoofing unification](http://link.springer.com/article/10.1007/s11416-009-0134-4#/page-1)"
publisher = "Journal in computer virology 6, no. 4"
date = "2010"
authors = "G. Prigent, F. Vichot, F. Harrouet"
abstract = "Nowadays, there are a variety of tools for easily identifying the TCP/IP stack's fingerprint of a target machine. IpMorph allows this fingerprint to be concealed, and even mimicks the fingerprint of a chosen TCP/IP stack. This is done through live session tracking and packet rewriting. Its effectiveness against tools such as Nmap, Xprobe2, Ring2, SinFP and p0f is also detailed."

###################################################################################################

[footer]
text = "Created with [Bootstrap](http://getbootstrap.com) and [Font Awesome](http://fortawesome.github.io/Font-Awesome/)"
