[header]
lang = "fr"
title = "Florian Vichot - CV"
headline = "Florian Vichot"
subtext = "développeur polyvalent"
location = "Sydney, Australie"
visa = "Résident australien"
phone = "+61 402 936 579"
email = "florian.vichot@gmail.com"
description = "Développeur expérimenté avec plus d'une dizaine d'années d'expérience, aussi bien en développement qu'en opérations. À l'aise avec des langages tels que le C, le C++ ou le Python, j'aspire avant tout à être polyvalent et à savoir résoudre une grande variété de problème, comme en témoigne la richesse de mon parcours. Intéressé principalement par des roles de devOps, ingénieur backend ou infrastructure, je suis ouvert à toutes propositions me permettant de travailler sur des problèmes épineux au sein d'une équipe talentueuse. Je suis en particulier attiré par la possibilité de travailler sur des projets open-source ou avec une composante sociale ou humanitaire."

github = "[fvichot](https://github.com/fvichot)"
stackoverflow = "[florian](http://stackoverflow.com/users/2984/florian)"
linkedin = "[fvichot](https://www.linkedin.com/in/fvichot/)"

skills = [
"Very autonomous and self-motivated, reliable and dependable team player",
"Experienced in leading teams, acting as technical referent, mentoring junior engineers",
"Truly implicated, committed to improving products and processes",
"Track record of improving code and infrastructure quality, performance and maintainability",
"Skilled at navigating and mastering complex software codebases",
"Dedicated to automate time-consuming and error-prone tasks",
]

###################################################################################################

[experience]
headline = "Expérience"

[[experience.item]]
title = "DevOps Engineer"
company = "[VMTech](https://vmtech.com.au/)"
location = "Sydney, Australia"
date = "August 2018 to now"
highlights = [
"Development from scratch of a customer-facing dashboard showing live stats, using *Python*, *SQLAlchemy* and *Flask*, using APIs from Splunk, ElasticSearch, ScienceLogic EM7, CommVault and ServiceNow.",
"Improving automation scripts (a mix of *Node.js*, *Python*, *Bash*) for monthly report generation.",
]
tags = ["Python", "Flask", "Gunicorn", "Nginx", "Frontend", "SQL-Server", "Bash", "Git", "Docker", "DevOps", "ITIL"]

[[experience.item]]
title = "Ingénieur Infrastructure et Réseau"
company = "[Wifirst](http://wifirst.fr/)"
location = "Paris, France"
date = "avril 2016 à mai 2018"
highlights = [
"Gestion d'un parc de 10 000 routers Linux, qui fournissent internet à ~500 000 personnes, avec *Ansible*.",
"",

"Developing *Python*/*Bash* services to configure *iptables*, routes, and supervision on Linux routers.",
"Designing and evolving our monitoring infrastructure for a large volume of data (150,000 devices supervised) using *Python*, *Nginx*, *Django*, *PostgreSQL*, *Redis*.",
"Automating & optimising image builds through *Jenkins*, which were tested using *LXC* and *Docker*.",
"Writing code to configure various network equipment: *Cisco*, *Zyxel*, *DLink*.",
"[Speaker](https://www.youtube.com/watch?v=0uasvz2DYos) at PyCon France 2017.",


"Correction de bugs et ajouts de fonctionnalité sur les services opérants dans le routeur déployé chez les clients, basé sur un Linux Debian, en charge du controle d'accès et de la qualité de service.",
"Maintien en condition opérationnelle d'une flotte d'environ 6 000 routeurs, déploiement de mise à jour par Ansible, sécurisation. Création d'outils pour faciliter cette tache.",
"Évaluation et selection de nouvelles bases matérielle pour le routeur Wifirst.",
"Portage des services et l'OS du routeur vers une nouvelle architecture, basée sur un SoC Broadcom.",
"Ajout de fonctionalités et correction de bug sur les logiciels internes, tel que notre interface de supervision, ou notre outil de gestion de configuration.",
"[Orateur](https://www.youtube.com/watch?v=0uasvz2DYos) à la PyCon France 2017"

]
tags = ["Python", "Django", "Nginx", "PostgreSQL", "Bash", "Git", "Ansible", "iptables", "Docker", "Jenkins", "Cisco", "Réseau", "DevOps", "Linux"]

[[experience.item]]
title = "Senior Software Engineer"
company = "[Inria, Asclepios Lab](https://team.inria.fr/asclepios/)"
location = "Sophia-Antipolis, France"
date = "March 2012 to April 2015"
highlights = [
"Lead developer on [medInria](http://med.inria.fr), a *C++*/*Qt* open-source medical image visualisation, processing and manipulation software, to add cardiac related functionalities.",
"Setup *CI/CD* using *Jenkins*, to test and build software on *Debian*, *Fedora*, *OSX* and *Windows 7+*.",
"Improved the reliability of medInria and its code quality by instituting code-reviews and a pull-request based workflow. Migrated the project to *GitHub*, reorganised, cleaned and simplified the source code, re-architected and updated the build/test system.",
"Evolved medInria's architecture to handle new functionalities, and transformed it into a framework for other projects using a plugin system.",
"Attended and presented at conferences (MICCAI), workshops (CTK), and contributed to scientific articles."
]
tags = ["C++", "Python", "Bash", "Git", "CMake", "Jenkins", "CI/CD", "Open-Source", "Qt", "VTK", "ITK", "Mac", "Windows", "Linux"]

[[experience.item]]
title = "Systems & Network Engineer"
company = "[Telecoms Without Borders](http://www.tsfi.org/)"
location = "Pau, France"
date = "Sept. 2010 to Oct. 2011, April 2015"
highlights = [
"Deployed on various international missions in response to humanitarian emergencies: floods, influx of refugees, cyclone, conflict or famine, for a total of 5 months on mission. Established telephone operations for populations, installed *network and satellite equipment* for NGOs and the UN. Provided trainings.",
"Maintained and evolved the NGO's infrastructure (*website*, *email servers*, *storage server*, *equipment database*, *OpenBSD firewall*).",
"Contributed to the TSFBox, a custom *Linux* router facilitating monitoring and optimization of internet connections provided during missions, with services written in *Perl*."
]
tags = ["Perl", "Python", "Bash", "iptables", "System administration", "Networks", "Satellites", "Linux"]


[[experience.item]]
title = "Software Engineer"
company = "[Diateam](http://www.diateam.net/)"
location = "Brest, France"
date = "June 2008 to April 2010, July/August 2007"
highlights = [
"Implemented in *C++/Qt4* a multithread RPC framework, as well as its *code generator* and *test suite*.",
"Lead developer on the Hynesim open source project (Hybrid Network Simulator): implementation in *C++/Qt4* of virtual network components, custom GUI widget and of wrappers around different virtualization technologies (*OpenVZ/LXC* containers, *Qemu/KVM* VMs) using *livbirt*. Speaker for conferences at OSSIRB and Hack.lu 2008.",
"Contributor to IpMorph : *TCP/IP stack* fingerprint spoofing for *containers* and *VMs*. Speaker during Hack.lu 2009. Co-authored a publication.",
]
tags = ["C", "C++", "PHP", "Python", "Open-Source", "Qt", "Multi-Thread", "LXC", "OpenVZ", "libvirt", "KVM", "OpenCL", "Mac", "Windows", "Linux"]

[[experience.item]]
title = "Internship"
company = "[Cognitive Robotics Lab (ENSTA)](http://cogrob.ensta-paristech.fr/)"
location = "Paris, France"
date = "Sept. 2007 to Jan. 2008"
highlights = [
"Implemented visual homing and localization *algorithms* using *\"bags of visual words\"* in [Urbi](https://en.wikipedia.org/wiki/URBI), as part of a topological navigation framework.",
"Ported the Urbi environment to a P3-DX robot.",
"This work was included in a [scientific publication](https://hal-ensta.archives-ouvertes.fr/hal-00641356)."
]
tags = ["C", "C++", "Urbi", "SVN", "Machine-Learning", "Linux", "Robotics"]

###################################################################################################

[projects]
headline = "Personal Projects"

[[projects.item]]
title = "Home lab on RPi cluster"
date = "2018 to now"
highlights = [
"Experiments in self-hosting, container orchestration and home automation."
]
tags = ["Raspbian", "Alpine", "Docker", "Docker-swarm", "Docker-compose", "NextCloud", "NAS"]

[[projects.item]]
title = "Robotics Club"
company = "[ENIB](https://www.enib.fr/)"
location = "Brest, France"
date = "2004 to 2010"
highlights = [
"Club secretary: sponsors engagement, communication, project management.",
"Lead developer on the robot's software (simulator, sensor acquisition, path planning, motor control)"
]
tags = ["C", "C++", "Qt", "OpenGL", "SVN", "Linux", "Embedded", "Robotics", "Algorithms"]

[[projects.item]]
title = "Server management"
date = "2011 to 2015"
highlights = [
"Server administrator for a club: configuration, security, supervision."
]
tags = ["Linux Debian", "iptables", "Apache", "PHP", "OwnCloud", "Zimbra", "OpenVPN", "IMAP", "SMTP", "LVM", "LUKS", "KVM", "LXC", "RAID"]

###################################################################################################

[skills]
headline = "Skills"
high = "Excellent"
medium = "Good"
low = "Basic"

[[skills.item]]
headline = "Languages"
high = ["C", "C++", "Python2/3", "Bash"]
medium = ["Go", "JavaScript", "Java", "Octave"]
low = ["Rust", "Haskell"]

[[skills.item]]
headline = "Tools and concepts"
high = ["Git", "Django", "Debugging", "CMake", "Qt", "Multi-threading", "CI/CD"]
medium = ["OpenCL", "SQL", "Algorithms", "Optimisation"]

[[skills.item]]
headline = "Networks & Servers"
high = ["Internet protocols", "Sysadmin", "Server security"]
medium = ["SSL", "OpenVPN", "IPSec", "AWS", "Satellite systems"]

[[skills.item]]
headline = "Platforms"
high = ["Linux (Debian/Fedora)", "Mac OS X", "Windows 7/8/10"]
medium = ["Cisco IOS", "ZynOS", "Digi"]
low = ["OpenBSD", "JunOS"]

###################################################################################################

[languages]
headline = "Languages"

[[languages.item]]
name = "French"
level = "Fluent (French citizen)"

[[languages.item]]
name = "English"
level = "Fluent (studied for three years in the UK, TOEFL iBT: 119/120, PTE: 90/90)"

[[languages.item]]
name = "Spanish"
level = "Intermediate (six months in South America)"

###################################################################################################

[education]
headline = "Education"
highlights = [
"[ENIB](https://www.enib.fr/en/), National Engineering School of Brest, France from 2003 to 2008 (Master's Degree in Engineering).",
"Artificial Intelligence online course, University of Stanford, 2012.",
"Machine Learning online course, Stanford University, 2015 ([Coursera](https://www.coursera.org/learn/machine-learning))."
]

###################################################################################################

[publications]
headline = "Publications"
authors = "Authors"
abstract = "Summary"

[[publications.item]]
title = "[Cardiac Interventional Guidance using Multimodal Data Processing and Visualisation: medInria as an Interoperability Platform](https://hal.inria.fr/hal-00813873/)"
publisher = "Midas Journal"
date = "2012"
authors = "F. Vichot, H. Cochet, B. Bleuzé, N. Toussaint, P. Jaïs, M. Sermesant"
abstract = "MedInria is a medical imaging software developed at Inria, which aims to provide clinicians with state-of-the-art algorithms for processing and visualising their images. In this article, we will focus on its use in pre-surgery preparation for cardiac interventions, and the difficulties arising from the lack of standardisation of certain data formats and visualisation conventions."

[[publications.item]]
title = "[IpMorph: fingerprinting spoofing unification](http://link.springer.com/article/10.1007/s11416-009-0134-4#/page-1)"
publisher = "Journal in computer virology 6, no. 4"
date = "2010"
authors = "G. Prigent, F. Vichot, F. Harrouet"
abstract = "Nowadays, there are a variety of tools for easily identifying the TCP/IP stack's fingerprint of a target machine. IpMorph allows this fingerprint to be concealed, and even mimicks the fingerprint of a chosen TCP/IP stack. This is done through live session tracking and packet rewriting. Its effectiveness against tools such as Nmap, Xprobe2, Ring2, SinFP and p0f is also detailed."
